import { NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

// A secure route that can be triggered by a Vercel Cron, GitHub Action, or standard cron daemon
// To trigger: POST /api/cron/birthday
// Headers: Authorization: Bearer YOUR_CRON_SECRET

export async function POST(request: Request) {
  try {
    // 1. Authorization Check
    const authHeader = request.headers.get("authorization");
    const cronSecret = process.env.CRON_SECRET || "default_local_secret";
    
    if (!authHeader || authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: "Unauthorized access" }, { status: 401 });
    }

    // 2. Date Verification (July 21st)
    // We get the current date. For local testing, we can pass a query param ?bypassDate=true
    const { searchParams } = new URL(request.url);
    const bypassDate = searchParams.get("bypassDate") === "true";
    
    const today = new Date();
    const isJuly21 = today.getMonth() === 6 && today.getDate() === 21; // Month is 0-indexed (6 = July)
    
    if (!isJuly21 && !bypassDate) {
      return NextResponse.json({ 
        message: "Cron executed. Today is not July 21st. No emails sent.",
        dateChecked: today.toISOString().split("T")[0]
      });
    }

    // 3. Retrieve Wishes to include in the email report/digest
    const dataFilePath = process.env.WISHES_DATA_PATH || path.join(/*turbopackIgnore: true*/ process.cwd(), "data", "wishes.json");
    let wishes = [];
    try {
      const fileContent = await fs.readFile(dataFilePath, "utf-8");
      wishes = JSON.parse(fileContent);
    } catch (e) {
      console.warn("Could not read wishes file for cron digest:", e);
    }

    // 4. Construct Email Digest
    const emailSubject = `Happy Birthday Mr. Julius Mattai! 🎂 Birthday Wishes Digest [July 21]`;
    const emailBody = `
      <h1>Happy Birthday, Minister Julius Mattai!</h1>
      <p>Today is July 21st, and your team and colleagues have compiled a board of floating birthday wishes for you.</p>
      
      <h2>Birthday Messages Summary (${wishes.length} wishes received):</h2>
      <ul>
        ${wishes.map((w: any) => `
          <li>
            <strong>${w.name}</strong> (${w.role}):<br/>
            <em>"${w.wish}"</em>
          </li>
        `).join("<br/>")}
      </ul>
      
      <p>Visit the live holographic birthday portal to see the wishes floating in space!</p>
      <hr/>
      <p><small>This email was automatically generated by the birthday cron job service.</small></p>
    `;

    // 5. Transactional Mailer Integration Guide (e.g. Resend)
    /*
    import { Resend } from 'resend';
    const resend = new Resend(process.env.RESEND_API_KEY);
    
    await resend.emails.send({
      from: 'Birthday Portal <portal@yourdomain.com>',
      to: ['ceo-julius-mattai@domain.com'], // Or the CEO's actual email
      cc: ['admin@domain.com'],
      subject: emailSubject,
      html: emailBody,
    });
    */

    console.log("Simulating Birthday Email Cron execution...");
    console.log("Subject:", emailSubject);
    console.log(`Sending email digest with ${wishes.length} wishes to CEO Mr. Julius Mattai...`);

    return NextResponse.json({
      success: true,
      message: "Birthday cron job executed successfully.",
      emailsSent: true,
      recipients: ["julius.mattai.ceo@example.com"],
      wishesProcessed: wishes.length,
      timestamp: new Date().toISOString()
    });

  } catch (error: any) {
    console.error("Cron job error:", error);
    return NextResponse.json({ error: "Cron job failed", details: error.message }, { status: 500 });
  }
}
